### ISSUE TITLE
提示邮件登录失败

### ISSUE THREAD

**Issue by wotlitn** [wuyufei1993/noip_active#1]
noip active run...

#########################################################################

2024-09-11 10:41:23 task run

email server login fail, check email account/config

2024-09-11 10:41:23 task end

-------------------------------------------------------------------------
ENV已经配置，在SHELL中有哪个地方可以查看配置文件？

**Comment by wuyufei1993** [comment]
重新构建的镜像还是直接用的dockerhub上的镜像？

**Comment by wuyufei1993** [comment]
更新了使用说明，可以检查下邮件服务器配置。ENV在容器内使用echo输出查看，例如EMAIL_USERNAME，
echo $EMAIL_USERNAME
